export const menuItems = [
  {
    label: "Home",
    to: "/",
    className: "main",
  },
  // {
  //   label: "Experience",
  //   to: "/work",
  //   className: "work",
  // },
  {
    label: "Projects",
    to: "/projects",
    className: "projects",
  },
  {
    label: "Articles",
    to: "/articles",
    className: "articles",
  },
  {
    label: "About",
    to: "/about",
    className: "about",
    lastItem: true,
  },
];

export const articlesList = [
  {
    link: "https://gonzalosimon.hashnode.dev/social-media-withmern-stack",
    class: "article-default",
    title: ["Social Media w/MERN Stack"],
    subtitle: "[Galeria is my first social media application.]",
    date: "5 Mar, 2022",
    index: "9",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/gallery-app-unsplash-api",
    class: "article-default",
    title: ["Gallery App Unsplash API"],
    subtitle: "[w/React [Infinite Scroll]]",
    date: "28 Jan, 2022",
    index: "8",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/javascript-algorithm-challenge-job-interview-challenge",
    class: "article-default",
    title: ["JavaScript Algorithm Challenge"],
    subtitle: "[Job Interview Challenge]",
    date: "5 Jan, 2021",
    index: "7",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/wikipedia-viewer-with-react",
    class: "article-default",
    title: ["Wikipedia Viewer", "\n", "w/ React"],
    subtitle: "[Personal Project]",
    date: "5 Jan, 2021",
    index: "6",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/to-do-app-with-react-and-redux-job-interview-challenge-1",
    class: "article-default",
    title: ["To-Do App", "\n", "w/ React & Redux"],
    subtitle: "[Job Interview Challenge]",
    date: "5 Jan, 2021",
    index: "5",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/how-i-got-started-coding",
    class: "article-default",
    title: ["How I got started coding"],
    date: "2 Jan, 2021",
    index: "4",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/wikipedia-viewer-with-react",
    class: "article-default",
    title: ["Wikipedia Viewer", "\n", "w/ React"],
    subtitle: "[Personal Project]",
    date: "5 Jan, 2021",
    index: "3",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/how-i-got-started-coding",
    class: "article-default",
    title: ["How I got started coding"],
    date: "2 Jan, 2021",
    index: "2",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-3-making-the-cpu-move",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 3]",
    date: "23 Dec, 2020",
    index: "2",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-1",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 1]",
    date: "December 12, 2020",
    index: "1",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-4",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 4]",
    date: "29 Dec, 2020",
    index: "0",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-3-making-the-cpu-move",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 3]",
    date: "23 Dec, 2020",
    index: "2",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-2",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 2]",
    date: "23 Dec, 2020",
    index: "1",
  },
  {
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-1",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 1]",
    date: "December 12, 2020",
    index: "0",
  },
];

export const projectsList = [
  {
    link: "https://socialgallery.netlify.app/",
    class: "project-default",
    name: "Galeria is my first social media application",
    title: "Social Media w/MERN Stack",
    tools: "React, Redux, Node, MongoDB",
    index: "12",
  },
  {
    link: "https://github.com/gonzalosimon/galleryapp/",
    class: "project-default",
    name: "Gallery App Unsplash API",
    title: "Gallery App Unsplash API w/React [Infinite Scroll]",
    tools: "JavaScript, React",
    index: "11",
  },
  {
    link: "https://github.com/gonzalosimon/footballgame/",
    class: "project-default",
    name: "Football Game with JavaScript",
    title: "Browser video-game",
    tools: "JavaScript Vanilla",
    index: "0",
  },
  {
    link: "https://github.com/Marcos-111/crazyPasswords",
    class: "project-default",
    name: "La Boutique de Marcos",
    title: "E-Commerce",
    tools: "Angular & TailwindCSS",
    index: "1",
  },
  {
    link: "https://github.com/gonzalosimon/url-shortener-microservice",
    class: "project-default",
    name: "URL Shortener",
    title: "URL Shortener Microservice",
    tools: "Node & MongoDB",
    index: "2",
  },
  {
    link: "https://github.com/gonzalosimon/socialMedia",
    class: "project-last",
    name: "Twitter Clone",
    title: "Social Media",
    tools: "MERN Stack",
    index: "3",
  },
  {
    link: "https://github.com/gonzalosimon/todoList-using-api-",
    class: "project-default",
    title: "Tasks App",
    name: "To-do App",
    tools: "MERN Stack - API",
    index: "4",
  },
  {
    link: "https://github.com/gonzalosimon/algorithms-solutions",
    class: "project-default",
    title: "Algorithms Repository",
    name: "+100 Algorithms",
    tools: "Mostly JS & Python",
    index: "5",
  },
  {
    link: "https://github.com/gonzalosimon/wikipedia-viewer",
    class: "project-default",
    title: "Wikipedia Viewer",
    name: "Wikipedia Finder",
    tools: "React & Redux",
    index: "6",
  },
  {
    link: "https://github.com/gonzalosimon/cities-slider",
    class: "project-last",
    title: "Cities Slider",
    name: "Argentine Cities Slider",
    tools: "React",
    index: "8",
  },
  {
    link: "https://github.com/gonzalosimon/jsc-graphic",
    class: "project-last",
    title: "Social Media",
    name: "Average Life Expectancy",
    tools: "JS Charting",
    index: "9",
  },
  {
    link: "https://github.com/gonzalosimon/treemap-diagram",
    class: "project-last",
    title: "Movies Treemap Diagram",
    name: "Treemap-diagram",
    tools: "D3",
    index: "10",
  },
];

export const clientsList = [
  {
    client: "Figo Pet Insurance",
    position: "Full-Stack Developer",
    tools: "JavaScript",
    date: "5 Mar, 2022",
    description: "I worked at Figo Pet Insurance",
    index: "5",
  },
  {
    client: "Norden",
    position: "Full-Stack Developer",
    tools: "JavaScript",
    date: "5 Mar, 2022",
    description: "I worked at Norden",
    index: "4",
  },
  {
    client: "Playboy Group Inc",
    position: "Full-Stack Developer",
    tools: "JavaScript",
    date: "5 Mar, 2022",
    description: "I worked at Playboy",
    index: "3",
  },
  {
    client: "Martin Marietta",
    position: "Full-Stack Developer",
    tools: "JavaScript",
    date: "5 Mar, 2022",
    description: "I worked at Martin Marietta",
    index: "2",
  },
  {
    client: "RETIA SOFT",
    position: "React Developer",
    tools: "React.js · JavaScript · Angular",
    date: " Apr 2021 - Sep 2021 · 6 mosApr 2021 - Sep 2021 · 6 mos ",
    description:
      "In my role as a software developer, I've had the opportunity to collaborate with a wide array of teams, leveraging the SCRUM methodology for efficient project management. One of my most significant experiences was developing a comprehensive software platform for a hospital. This involved delving into the intricacies of React hooks, which significantly improved our code's structure and functionality. I also took on the challenge of creating new forms and designing reusable components to enhance our project's efficiency. One of the most rewarding aspects was managing complex data states, ensuring accuracy and reliability. Working closely with other developers and stakeholders, we diligently hit our project milestones. Ultimately, we were successful in creating a user-friendly and effective platform that significantly enhanced the hospital's operations.",
    index: "1",
  },
  {
    client: "FREELANCE",
    position: "Full-Stack Developer",
    tools: "Next.js · React.js · Python (Programming Language)",
    date: "December, 2019 - April 2021",
    description:
      "As a freelance React developer, I spent four months enhancing an e-commerce website built with Next.js. My role was multifaceted, involving bug fixes and performance improvements for a better user experience, while also expanding the site's capabilities through the addition of new features, pages, and sections. Working in a small team, we collaboratively met project milestones, and my responsibilities also included providing continuous technical support and guidance to ensure smooth and efficient website operation. This invaluable experience reinforced my technical skills and underscored the significance of teamwork and proactive problem-solving in delivering high-quality digital solutions.",
    index: "0",
  },
];
