export const articlesList = [
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/social-media-withmern-stack",
    class: "article-default",
    title: ["Social Media w/MERN Stack"],
    subtitle: "[Galeria is my first social media application.]",
    date: "5 Mar, 2022",
    dateClass: "article-date two-line",
    index: "9",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/gallery-app-unsplash-api",
    class: "article-default",
    title: ["Gallery App Unsplash API"],
    subtitle: "[w/React [Infinite Scroll]]",
    date: "28 Jan, 2022",
    dateClass: "article-date two-line",
    index: "8",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/javascript-algorithm-challenge-job-interview-challenge",
    class: "article-default",
    title: ["JavaScript Algorithm Challenge"],
    subtitle: "[Job Interview Challenge]",
    date: "5 Jan, 2021",
    dateClass: "article-date two-line",
    index: "7",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/wikipedia-viewer-with-react",
    class: "article-default",
    title: ["Wikipedia Viewer", "\n", "w/ React"],
    subtitle: "[Personal Project]",
    date: "5 Jan, 2021",
    dateClass: "article-date two-line",
    index: "6",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/to-do-app-with-react-and-redux-job-interview-challenge-1",
    class: "article-default",
    title: ["To-Do App", "\n", "w/ React & Redux"],
    subtitle: "[Job Interview Challenge]",
    date: "5 Jan, 2021",
    dateClass: "article-date two-line",
    index: "5",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/how-i-got-started-coding",
    class: "article-default",
    title: ["How I got started coding"],
    date: "2 Jan, 2021",
    dateClass: "article-date two-line",
    index: "4",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/wikipedia-viewer-with-react",
    class: "article-default",
    title: ["Wikipedia Viewer", "\n", "w/ React"],
    subtitle: "[Personal Project]",
    date: "5 Jan, 2021",
    dateClass: "article-date two-line",
    index: "3",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/how-i-got-started-coding",
    class: "article-default",
    title: ["How I got started coding"],
    date: "2 Jan, 2021",
    dateClass: "article-date two-line",
    index: "2",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-3-making-the-cpu-move",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 3]",
    date: "23 Dec, 2020",
    dateClass: "article-date two-line",
    index: "2",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-1",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 1]",
    date: "December 12, 2020",
    dateClass: "article-date two-line",
    index: "1",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-4",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 4]",
    date: "29 Dec, 2020",
    dateClass: "article-date two-line",
    index: "0",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-3-making-the-cpu-move",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 3]",
    date: "23 Dec, 2020",
    dateClass: "article-date two-line",
    index: "2",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-2",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 2]",
    date: "23 Dec, 2020",
    dateClass: "article-date two-line",
    index: "1",
  },
  {
    aos: "",
    link: "https://gonzalosimon.hashnode.dev/football-game-with-javascript-part-1",
    class: "article-default",
    title: ["Football Game", "\n", "With JavaScript"],
    subtitle: "[Part 1]",
    date: "December 12, 2020",
    dateClass: "article-date two-line",
    index: "0",
  },
];

export const projectsList = [
  {
    link: "https://socialgallery.netlify.app/",
    aos: "fade-up",
    class: "project-default",
    name: "Galeria is my first social media application",
    title: "Social Media w/MERN Stack",
    tools: "React, Redux, Node, MongoDB",
    index: "12",
  },
  {
    link: "https://github.com/gonzalosimon/galleryapp/",
    aos: "fade-up",
    class: "project-default",
    name: "Gallery App Unsplash API",
    title: "Gallery App Unsplash API w/React [Infinite Scroll]",
    tools: "JavaScript, React",
    index: "11",
  },
  {
    link: "https://github.com/gonzalosimon/footballgame/",
    aos: "fade-up",
    class: "project-default",
    name: "Football Game with JavaScript",
    title: "Browser video-game",
    tools: "JavaScript Vanilla",
    index: "0",
  },
  {
    link: "https://github.com/Marcos-111/crazyPasswords",
    aos: "fade-up",
    class: "project-default",
    name: "La Boutique de Marcos",
    title: "E-Commerce",
    tools: "Angular & TailwindCSS",
    index: "1",
  },
  {
    link: "https://github.com/gonzalosimon/url-shortener-microservice",
    aos: "fade-up",
    class: "project-default",
    name: "URL Shortener",
    title: "URL Shortener Microservice",
    tools: "Node & MongoDB",
    index: "2",
  },
  {
    link: "https://github.com/gonzalosimon/socialMedia",
    aos: "fade-up",
    class: "project-last",
    name: "Twitter Clone",
    title: "Social Media",
    tools: "MERN Stack",
    index: "3",
  },
  {
    link: "https://github.com/gonzalosimon/todoList-using-api-",
    aos: "fade-up",
    class: "project-default",
    title: "Tasks App",
    name: "To-do App",
    tools: "MERN Stack - API",
    index: "4",
  },
  {
    link: "https://github.com/gonzalosimon/algorithms-solutions",
    aos: "fade-up",
    class: "project-default",
    title: "Algorithms Repository",
    name: "+100 Algorithms",
    tools: "Mostly JS & Python",
    index: "5",
  },
  {
    link: "https://github.com/gonzalosimon/wikipedia-viewer",
    aos: "fade-up",
    class: "project-default",
    title: "Wikipedia Viewer",
    name: "Wikipedia Finder",
    tools: "React & Redux",
    index: "6",
  },
  {
    link: "https://github.com/gonzalosimon/cities-slider",
    aos: "fade-up",
    class: "project-last",
    title: "Cities Slider",
    name: "Argentine Cities Slider",
    tools: "React",
    index: "8",
  },
  {
    link: "https://github.com/gonzalosimon/jsc-graphic",
    aos: "fade-up",
    class: "project-last",
    title: "Social Media",
    name: "Average Life Expectancy",
    tools: "JS Charting",
    index: "9",
  },
  {
    link: "https://github.com/gonzalosimon/treemap-diagram",
    aos: "fade-up",
    class: "project-last",
    title: "Movies Treemap Diagram",
    name: "Treemap-diagram",
    tools: "D3",
    index: "10",
  },
];

export const menuItems = [
  {
    label: "Home",
    to: "/",
    className: "main",
  },
  // {
  //   label: "Experience",
  //   to: "/work",
  //   className: "work",
  // },
  {
    label: "Projects",
    to: "/projects",
    className: "projects",
  },
  {
    label: "Articles",
    to: "/articles",
    className: "articles",
  },
  {
    label: "About",
    to: "/about",
    className: "about",
    lastItem: true,
  },
];

export const clientsList = [];
